async function verifyCalendarSync(page){
 const checks=[];const check=(ok,name)=>{if(!ok)throw Error(name);checks.push(name);};
 const root='http://127.0.0.1:1439/personal-preview.html?calendar-sync';
 await page.goto(root);
 await page.setViewportSize({width:1280,height:900});
 await page.getByRole('button',{name:'+ Создать',exact:true}).click();
 const dialog=page.getByRole('dialog',{name:'Создание записи'});
 await dialog.getByRole('textbox',{name:'Название записи',exact:true}).fill('Дизайн-ревью команды');
 check(await dialog.getByRole('combobox').locator('option').count()===1,'Read-only calendars excluded');
 check(await dialog.getByRole('textbox',{name:'Описание записи'}).count()===0,'Details hidden initially');
 check(await dialog.evaluate(e=>e.getBoundingClientRect().height)<470,'Compact initial card under 470px');
 await page.screenshot({path:'output/playwright/calendar-create-compact.png'});
 await dialog.getByRole('button',{name:'Детали',exact:true}).click();
 await dialog.getByRole('textbox',{name:'Описание записи'}).fill('Демонстрация создания события в исходном календаре');
 await page.screenshot({path:'output/playwright/calendar-create-wide.png'});
 await dialog.getByRole('button',{name:'Свернуть детали',exact:true}).click();
 await dialog.getByRole('button',{name:'Детали · есть описание',exact:true}).click();
 check(await dialog.getByRole('textbox',{name:'Описание записи'}).inputValue()==='Демонстрация создания события в исходном календаре','Description survives detail collapse');
 await dialog.getByRole('button',{name:'Свернуть детали',exact:true}).click();
 await dialog.getByRole('button',{name:'Создать',exact:true}).click();
 await dialog.getByRole('heading',{name:'Создано в календаре'}).waitFor();
 let draft=await page.evaluate(()=>JSON.parse(document.documentElement.dataset.calendarDraft));
 check(draft.kind==='event'&&!draft.all_day&&draft.start<draft.end,'Timed event payload and confirmed save');
 await dialog.getByRole('button',{name:'Готово',exact:true}).click();
 await page.getByRole('button',{name:'+ Создать',exact:true}).click();
 await dialog.getByRole('textbox',{name:'Название записи',exact:true}).fill('День планирования');
 await dialog.getByRole('checkbox',{name:'Весь день',exact:true}).check();
 await dialog.getByRole('textbox',{name:'Дата начала'}).fill('2026-09-28');
 await dialog.getByRole('button',{name:'Детали',exact:true}).click();
 await dialog.getByRole('textbox',{name:'Дата окончания'}).fill('2026-09-30');
 await dialog.getByRole('button',{name:'Создать',exact:true}).click();
 await dialog.getByRole('heading',{name:'Создано в календаре'}).waitFor();
 draft=await page.evaluate(()=>JSON.parse(document.documentElement.dataset.calendarDraft));
 check(draft.all_day&&draft.end==='2026-10-01','Multi-day all-day end exclusive');
 await dialog.getByRole('button',{name:'Готово',exact:true}).click();
 await page.getByRole('button',{name:'+ Создать',exact:true}).click();
 await dialog.getByRole('button',{name:'Задача',exact:true}).click();
 check(await dialog.getByRole('textbox',{name:'Время начала'}).count()===0,'No fabricated Google task time');
 await dialog.getByRole('textbox',{name:'Название записи',exact:true}).fill('Новая идея без срока');
 await dialog.getByRole('textbox',{name:'Дата начала'}).fill('');
 await page.setViewportSize({width:390,height:780});
 await page.screenshot({path:'output/playwright/calendar-create-narrow.png'});
 check(await dialog.evaluate(e=>e.getBoundingClientRect().right<=innerWidth&&e.getBoundingClientRect().left>=0),'Narrow composer fits viewport');
 await dialog.getByRole('button',{name:'Создать',exact:true}).click();
 await dialog.getByRole('heading',{name:'Создано в календаре'}).waitFor();
 draft=await page.evaluate(()=>JSON.parse(document.documentElement.dataset.calendarDraft));
 check(draft.kind==='task'&&draft.start===null&&draft.end===null,'Undated task saves without fake date');
 await dialog.getByRole('button',{name:'Готово',exact:true}).click();
 await page.setViewportSize({width:1280,height:900});
 await page.getByRole('button',{name:/^Задачи ·/}).click();
 const tasks=page.locator('.cs-tasks');
 await tasks.getByText('Новая идея без срока',{exact:true}).waitFor();
 check(await tasks.getByText('Идея без срока',{exact:true}).isVisible(),'Existing undated tasks shown');
 await tasks.getByRole('checkbox',{name:'Выполнено: Подготовить материалы',exact:true}).click();
 await tasks.getByRole('checkbox',{name:'Выполнено: Подготовить материалы',exact:true}).waitFor({state:'hidden'});
 await tasks.getByRole('checkbox',{name:'Выполненные',exact:true}).check();
 check(await tasks.getByRole('checkbox',{name:'Выполнено: Подготовить материалы',exact:true}).isChecked(),'Completion persists and completed filter works');
 await page.screenshot({path:'output/playwright/calendar-tasks.png'});
 await page.getByRole('button',{name:'Показать настройки',exact:true}).click();
 check(await page.getByRole('button',{name:'Подключить Google',exact:true}).isEnabled(),'Consumer connect button');
 check(await page.getByRole('button',{name:'Подключить Яндекс',exact:true}).isDisabled(),'Unapproved Yandex connector gated');
 check(await page.locator('input').evaluateAll(nodes=>nodes.every(n=>!/(client.?id|secret|пароль)/i.test((n.placeholder||'')+' '+(n.getAttribute('aria-label')||'')))),'No consumer client ID or credential inputs');
 await page.screenshot({path:'output/playwright/calendar-accounts.png',fullPage:true});
 await page.goto(root+'&calendar-write-error');
 await page.getByRole('button',{name:'+ Создать',exact:true}).click();
 await dialog.getByRole('textbox',{name:'Название записи',exact:true}).fill('Проверка ошибки');
 await dialog.getByRole('button',{name:'Создать',exact:true}).click();
 await dialog.getByRole('alert').waitFor();
 check(await dialog.getByRole('textbox',{name:'Название записи',exact:true}).inputValue()==='Проверка ошибки','Failed save retains draft');
 check(await dialog.getByRole('heading',{name:'Создано в календаре'}).count()===0,'No success on rejected write');
 await page.goto(root+'&calendar-write-unknown');
 await page.getByRole('button',{name:'+ Создать',exact:true}).click();
 await dialog.getByRole('textbox',{name:'Название записи',exact:true}).fill('Не дублировать');
 await dialog.getByRole('button',{name:'Создать',exact:true}).click();
 await dialog.getByRole('alert').waitFor();
 check(await dialog.getByRole('button',{name:'Создать',exact:true}).isDisabled(),'Uncertain result blocks duplicate submission');
 await page.goto('http://127.0.0.1:1439/personal-preview.html');
 await page.getByRole('button',{name:'Показать настройки',exact:true}).click();
 check(await page.getByRole('button',{name:'Подключить Google',exact:true}).isDisabled(),'Unconfigured production-like build explains unavailable sign-in');
 await page.goto(root+'&calendar-disconnected');
 await page.getByRole('button',{name:'Показать настройки',exact:true}).click();
 await page.getByRole('button',{name:'Подключить Google',exact:true}).click();
 await page.getByText('Демонстрационный Google',{exact:true}).waitFor();
 checks.push('Synthetic connection updates account list');
 return {passed:checks.length,checks,scope:'Synthetic browser bridge, no real account calls'};
}
