import {useEffect,useState} from 'react';
import {Launcher} from '../src/launcher/Launcher';
import {MixerPanel} from '../src/system/MixerPanel';
import {LayoutEditor} from '../src/settings/LayoutEditor';
import {useBloomAppearance} from '../src/appearance/BloomAppearance';
export function DesktopDemo(){
 useBloomAppearance();const [page,setPage]=useState(new URLSearchParams(location.search).get('desktop')||'search'),[status,setStatus]=useState('');
 useEffect(()=>{const select=(e:Event)=>setPage((e as CustomEvent).detail),action=(e:Event)=>setStatus('Демо: '+(e as CustomEvent).detail);window.addEventListener('bloom-demo-page',select);window.addEventListener('bloom-demo-action',action);return()=>{window.removeEventListener('bloom-demo-page',select);window.removeEventListener('bloom-demo-action',action);};},[]);
 return <div className="desktop-demo"><header><b>dinox</b><span>Демонстрация · Windows не изменяется</span></header><nav>{[['search','Поиск'],['mixer','Звук'],['layout','Рабочий стол']].map(([id,label])=><button key={id} aria-pressed={page===id} onClick={()=>{setPage(id);setStatus('');}}>{label}</button>)}</nav><div role="status" className="desktop-demo-status">{status}</div><div className={'desktop-demo-panel '+page}>{page==='search'?<Launcher onCopy={async text=>{if(new URLSearchParams(location.search).has('copy-error'))throw new Error('Clipboard blocked');document.documentElement.dataset.copiedCalculation=text;}} onClose={()=>{setPage('closed');}}/>:page==='mixer'?<MixerPanel onClose={()=>setPage('closed')}/>:page==='layout'?<LayoutEditor/>:<button onClick={()=>setPage('search')}>Открыть поиск снова</button>}</div><style>{`.desktop-demo{min-height:100vh;background:radial-gradient(ellipse at 70% 0,#292930,#111114 70%);padding:32px 20px 60px;color:#eee;font:13px 'Segoe UI';box-sizing:border-box}.desktop-demo>header{display:flex;justify-content:space-between;gap:20px;max-width:880px;margin:auto;align-items:center}.desktop-demo>header b{font-size:30px;letter-spacing:-1px}.desktop-demo>header span{color:#999;font-size:11px}.desktop-demo>nav{display:flex;justify-content:center;gap:8px;margin:30px auto 0}.desktop-demo>nav button,.desktop-demo-panel>button{background:#191919;color:#ccc;border:1px solid #333;border-radius:9px;padding:10px 20px;cursor:pointer}.desktop-demo>nav button[aria-pressed=true]{background:#eee;color:#111}.desktop-demo-status{font-size:12px;text-align:center;color:#bbb;min-height:35px;padding:10px;overflow-wrap:anywhere}.desktop-demo-panel{margin:auto;max-width:680px;box-shadow:0 24px 100px #0005;border-radius:20px;background:#000}.desktop-demo-panel.search{height:530px}.desktop-demo-panel.mixer{max-width:390px;padding:24px}.desktop-demo-panel.layout{padding:24px}.desktop-demo-panel.closed{padding:30px;text-align:center}@media(max-width:480px){.desktop-demo{padding:18px 10px 30px}.desktop-demo-panel.layout,.desktop-demo-panel.mixer{padding:16px}.desktop-demo-panel.search{height:min(580px,78vh)}}`}</style></div>;
}
