async function verifyNoteReliability(page){
 const checks=[],check=(ok,name)=>{if(!ok)throw new Error(name);checks.push(name);};
 await page.goto('http://127.0.0.1:1439/personal-preview.html?desktop=widgets');
 await page.locator('.dn-widget').getByRole('button',{name:'Новая заметка',exact:true}).click();
 const lib=page.getByRole('dialog',{name:'Библиотека заметок'}),title=lib.getByRole('textbox',{name:'Название заметки'});
 await title.fill('Recovery check');await page.waitForFunction(()=>!Object.keys(localStorage).some(k=>k.startsWith('dinox-sticky-recovery:')));
 await page.evaluate(()=>{window.__restoreNoteTx=IDBDatabase.prototype.transaction;IDBDatabase.prototype.transaction=function(stores,mode,...rest){if(this.name==='dinox-sticky-notes'&&mode==='readwrite')throw new DOMException('Disk full','QuotaExceededError');return window.__restoreNoteTx.call(this,stores,mode,...rest);};});
 await title.fill('Unsaved draft retained');await lib.locator('.dn-store-error').first().waitFor();await lib.getByRole('button',{name:'Закрыть библиотеку',exact:true}).click();check(await lib.isVisible(),'Save failure blocks closing library');check(await title.inputValue()==='Unsaved draft retained','Failed write retains draft');
 await page.evaluate(()=>{IDBDatabase.prototype.transaction=window.__restoreNoteTx;delete window.__restoreNoteTx;});await lib.getByRole('button',{name:'Повторить сохранение',exact:true}).click();await page.waitForFunction(()=>!Object.keys(localStorage).some(k=>k.startsWith('dinox-sticky-recovery:')));check(true,'Retry commits retained draft');
 // Simulate a concurrent commit before its broadcast reaches this editor.
 await page.evaluate(async()=>{const db=await new Promise(resolve=>{const r=indexedDB.open('dinox-sticky-notes');r.onsuccess=()=>resolve(r.result);});await new Promise(resolve=>{const tx=db.transaction('notes','readwrite'),store=tx.objectStore('notes'),r=store.getAll();r.onsuccess=()=>{const n=r.result.find(n=>n.title==='Unsaved draft retained');store.put({...n,title:'Remote version',revision:n.revision+1});};tx.oncomplete=resolve;});db.close();});
 await title.fill('My concurrent draft');await lib.getByRole('button',{name:'Сохранить отдельную копию',exact:true}).waitFor();check(true,'Concurrent revision is detected');await lib.getByRole('button',{name:'Сохранить отдельную копию',exact:true}).click();await page.waitForFunction(()=>!Object.keys(localStorage).some(k=>k.startsWith('dinox-sticky-recovery:')));await lib.getByRole('button',{name:'Открыть заметку: Remote version',exact:true}).waitFor();check(await lib.getByRole('button',{name:'Открыть заметку: My concurrent draft',exact:true}).count()===1,'Conflict keeps both versions');
 await page.evaluate(async()=>{const db=await new Promise(resolve=>{const r=indexedDB.open('dinox-sticky-notes');r.onsuccess=()=>resolve(r.result);});await new Promise(resolve=>{const tx=db.transaction('notes','readwrite');for(let i=0;i<80;i++)tx.objectStore('notes').put({id:crypto.randomUUID(),title:`Batch note ${i}`,doc:{type:'doc',content:[{type:'paragraph'}]},color:'blue',pinned:false,source:'',created:Date.now(),updated:Date.now(),revision:1,deletedAt:null});tx.oncomplete=resolve;});db.close();const ch=new BroadcastChannel('dinox-sticky-notes');ch.postMessage('fixture');ch.close();});
 await lib.getByRole('textbox',{name:'Поиск заметок'}).fill('Batch note');await lib.getByRole('button',{name:'Показать ещё',exact:true}).waitFor();check(await lib.locator('.dn-note-preview').count()===60,'Large library renders first 60 notes');await lib.getByRole('button',{name:'Показать ещё',exact:true}).click();check(await lib.locator('.dn-note-preview').count()===80,'Remaining notes can be loaded');
 await lib.getByRole('button',{name:'Выбрать несколько заметок'}).click();await lib.getByRole('button',{name:'Выбрать все',exact:true}).click();await lib.getByRole('button',{name:'В корзину',exact:true}).click();await lib.getByRole('button',{name:'Корзина',exact:true}).click();await lib.getByRole('button',{name:'Показать ещё',exact:true}).waitFor();check(true,'Bulk delete moves every matching note to trash');await lib.getByRole('button',{name:'Выбрать все',exact:true}).click();await lib.getByRole('button',{name:'Удалить навсегда',exact:true}).click();await lib.getByRole('button',{name:'Отмена',exact:true}).click();check(await lib.getByRole('button',{name:'Показать ещё',exact:true}).isVisible(),'Permanent delete can be cancelled');await lib.getByRole('button',{name:'Удалить навсегда',exact:true}).click();await lib.getByRole('button',{name:'Подтвердить удаление',exact:true}).click();await lib.getByText('Ничего не найдено',{exact:true}).waitFor();check(await lib.locator('.dn-note-preview').count()===0,'Confirmed permanent deletion removes selected notes');
 return {passed:checks.length,checks};
}
