// Synthetic browser profile only; never run against personal native data.
async function verifyStickyNotes(page){
 const checks=[],check=(ok,name)=>{if(!ok)throw new Error(name);checks.push(name);};
 const base='http://127.0.0.1:1439/personal-preview.html?desktop=widgets';
 await page.setViewportSize({width:1440,height:1000});await page.goto(base);
 await page.evaluate(async()=>{const database=await new Promise(resolve=>{const request=indexedDB.open('dinox-sticky-notes',1);request.onsuccess=()=>resolve(request.result);});await new Promise(resolve=>{const tx=database.transaction(['notes','meta'],'readwrite');tx.objectStore('notes').clear();tx.objectStore('meta').clear();tx.oncomplete=resolve;});database.close();for(const key of Object.keys(localStorage))if(key.startsWith('dinox-sticky-recovery:'))localStorage.removeItem(key);localStorage.setItem('dinox-widget-note-data',JSON.stringify('Заметка из прошлой версии'));});await page.reload();
 await page.locator('.dn-widget').getByRole('button',{name:/Заметка из прошлой версии/}).waitFor();check(true,'Old note migrates into library');
 await page.locator('.dn-widget').getByRole('button',{name:'Новая заметка',exact:true}).click();
 const library=page.getByRole('dialog',{name:'Библиотека заметок'}),title=library.getByRole('textbox',{name:'Название заметки'}),body=library.getByRole('textbox',{name:'Текст заметки'});
 await title.fill('Дизайн Dinox');await body.fill('Идеи для следующего релиза');
 await body.press('Control+a');await library.getByRole('button',{name:'Жирный',exact:true}).click();
 check(await body.locator('strong').innerText()==='Идеи для следующего релиза','Formatting applies to selected text');
 await library.getByRole('button',{name:'Фиолетовый',exact:true}).click();await library.getByRole('button',{name:'Закрепить заметку',exact:true}).click();
 await library.getByRole('button',{name:'Источник заметки',exact:true}).click();await library.getByRole('textbox',{name:'Ссылка на источник',exact:true}).fill('https://example.com/design');await library.getByRole('button',{name:'Сохранить ссылку',exact:true}).click();
 await library.getByRole('button',{name:'https://example.com/design',exact:true}).click();check(await page.evaluate(()=>document.documentElement.dataset.widgetTarget)==='https://example.com/design','Source opens through native command contract');
 await body.press('Control+End');await library.locator('input[type=file]').setInputFiles('C:/Users/klimi/APPS_projects/Dinox-Desktop/tests/fixtures/sticky-image.png');
 await body.locator('img').waitFor();check(true,'User image added locally');
 await library.getByRole('button',{name:'Закрыть библиотеку',exact:true}).click();await page.reload();await page.locator('.dn-widget').getByRole('button',{name:'Все заметки',exact:true}).click();
 await title.waitFor();check(await title.inputValue()==='Дизайн Dinox','Note title persists after reload');check(await body.locator('strong').count()===1&&await body.locator('img').count()===1,'Formatting and image persist');check(await library.getByRole('button',{name:'Фиолетовый',exact:true}).getAttribute('aria-pressed')==='true','Color persists');
 await library.getByRole('button',{name:'Открыть отдельным окном',exact:true}).click();const popup=page.locator('.dn-popout');await popup.waitFor();await popup.getByRole('textbox',{name:'Название заметки'}).fill('Дизайн Dinox — правки');check(await title.inputValue()==='Дизайн Dinox — правки','Separate window edits update library');await popup.getByRole('button',{name:'Поверх других окон'}).click();check(await page.evaluate(()=>document.documentElement.dataset.noteTop)==='true','Topmost command dispatched');await popup.getByRole('button',{name:'Закрыть заметку',exact:true}).click();
 await library.getByRole('button',{name:'Создать копию',exact:true}).click();await title.fill('Список покупок');await body.fill('Кофе\nБлокнот');await body.press('Control+a');await library.getByRole('button',{name:'Список',exact:true}).click();check(await body.locator('li').count()===2,'Multiline text becomes bullet list');
 await library.getByRole('textbox',{name:'Поиск заметок'}).fill('покупок');check(await library.locator('.dn-note-preview').count()===1,'Library search filters notes');await library.getByRole('textbox',{name:'Поиск заметок'}).fill('');
 await library.getByRole('button',{name:'Удалить заметку',exact:true}).click();await library.getByRole('button',{name:'Отменить удаление',exact:true}).click();check(await library.getByRole('button',{name:'Открыть заметку: Список покупок',exact:true}).count()===1,'Delete can be undone');
 await library.getByRole('button',{name:'Открыть заметку: Список покупок',exact:true}).click();await library.getByRole('button',{name:'Удалить заметку',exact:true}).click();await library.getByRole('button',{name:'Корзина',exact:true}).click();await library.getByRole('button',{name:'Открыть заметку: Список покупок',exact:true}).click();await page.waitForFunction(()=>document.querySelector('.dn-paper [role=textbox]')?.getAttribute('contenteditable')==='false');check(await body.getAttribute('contenteditable')==='false','Trash is read-only');await library.getByRole('button',{name:'Восстановить заметку',exact:true}).click();await library.getByRole('button',{name:/^Все ·/}).click();check(await library.getByRole('button',{name:'Открыть заметку: Список покупок',exact:true}).count()===1,'Trash restoration works');
 await library.getByRole('button',{name:'Открыть заметку: Дизайн Dinox — правки',exact:true}).click();
 for(const width of [800,390]){await page.setViewportSize({width,height:850});check(await library.evaluate(e=>e.scrollWidth===e.clientWidth),`Library fits ${width}px`);check(await body.isVisible(),`Editor reachable at ${width}px`);}
 await library.getByRole('button',{name:'К списку',exact:true}).click();check(await library.getByRole('textbox',{name:'Поиск заметок'}).isVisible(),'Mobile back returns to list');
 await page.setViewportSize({width:1440,height:1000});await library.getByRole('button',{name:'Открыть заметку: Дизайн Dinox — правки',exact:true}).click();await title.focus();await page.keyboard.press('Escape');await library.waitFor({state:'hidden'});check(await page.locator('.widget-board').isVisible(),'Escape closes library without closing board');
 await page.locator('.dn-widget').getByRole('button',{name:'Все заметки',exact:true}).click();
 return {passed:checks.length,checks};
}
