async function verifyNoteWindows(page){
 const checks=[],check=(ok,name)=>{if(!ok)throw new Error(name);checks.push(name);};
 const base='http://127.0.0.1:1439/personal-preview.html?desktop=widgets';await page.goto(base);
 await page.locator('.dn-widget').getByRole('button',{name:'Новая заметка',exact:true}).click();const lib=page.getByRole('dialog',{name:'Библиотека заметок'});await lib.getByRole('textbox',{name:'Название заметки'}).fill('Shared window check');await lib.getByRole('button',{name:'Закрыть библиотеку'}).click();await page.locator('.dn-widget').getByRole('button',{name:'Все заметки',exact:true}).click();
 await lib.getByRole('button',{name:'Открыть заметку: Shared window check',exact:true}).click();const second=await page.context().newPage();try{
  await second.goto(base);await second.locator('.dn-widget').getByRole('button',{name:'Все заметки',exact:true}).click();const other=second.getByRole('dialog',{name:'Библиотека заметок'});await other.getByRole('button',{name:'Открыть заметку: Shared window check',exact:true}).click();await other.getByRole('textbox',{name:'Название заметки'}).fill('Shared edit delivered');await page.waitForFunction(()=>document.querySelector('.dn-title')?.value==='Shared edit delivered');check(true,'Broadcast updates a separate browser window');
  await lib.getByRole('textbox',{name:'Текст заметки'}).fill('Text from the first window');await second.waitForFunction(()=>document.querySelector('.dn-paper')?.textContent==='Text from the first window');check(true,'Document changes propagate in both directions');
 }finally{await second.close();}
 await page.waitForFunction(()=>!Object.keys(localStorage).some(k=>k.startsWith('dinox-sticky-recovery:')));
 await page.evaluate(()=>{const original=IDBDatabase.prototype.transaction;IDBDatabase.prototype.transaction=function(stores,mode,...rest){if(this.name==='dinox-sticky-notes'&&mode==='readwrite')throw new Error('Simulated unavailable disk');return original.call(this,stores,mode,...rest);};});await lib.getByRole('textbox',{name:'Название заметки'}).fill('Recovered after interrupted write');await lib.locator('.dn-store-error').first().waitFor();await page.reload();await page.locator('.dn-widget').getByRole('button',{name:'Все заметки',exact:true}).click();await lib.getByRole('button',{name:'Открыть заметку: Recovered after interrupted write',exact:true}).waitFor();await page.waitForFunction(()=>!Object.keys(localStorage).some(k=>k.startsWith('dinox-sticky-recovery:')));check(true,'Recovery journal saves interrupted draft after reload');
 return {passed:checks.length,checks};
}
