// Run against the synthetic Vite preview. No native windows or user calendars.
async function verifyWidgets(page) {
  const base='http://127.0.0.1:1439/personal-preview.html?desktop=widgets', checks=[];
  const check=(ok,name)=>{if(!ok)throw new Error(name);checks.push(name);};
  const go=async(suffix='')=>{await page.goto(base+suffix);await page.getByRole('heading',{name:'Мой день',exact:true}).waitFor();};
  const settings=async()=>{await page.getByRole('button',{name:'Настроить виджеты'}).click();await page.getByRole('combobox',{name:'Горячая клавиша виджетов'}).waitFor();};
  await page.setViewportSize({width:1280,height:920});await page.goto(base);
  await page.evaluate(()=>{
    localStorage.setItem('bloom-language','ru');localStorage.removeItem('dinox-widget-focus-state');
    const saved=JSON.parse(localStorage.getItem('dinox-v4-demo-settings')||'{}');
    Object.assign(saved,{'bloom-language':'ru','dinox-widgets-enabled':'true','dinox-widgets-shortcut':'custom:3:87','dinox-widget-today':'true','dinox-widget-calendar':'true','dinox-widget-focus':'true'});
    for(const [key,value]of Object.entries(saved))localStorage.setItem(key,String(value));
    localStorage.setItem('dinox-v4-demo-settings',JSON.stringify(saved));
  });await go();
  await page.locator('.wb-today .wb-event').first().waitFor();
  check(await page.locator('.wb-card').count()===7,'Seven widgets');
  await page.getByRole('textbox',{name:'Задача для фокуса'}).fill('Подготовить презентацию');
  await page.getByRole('button',{name:'Начать',exact:true}).click();await page.getByRole('button',{name:'Пауза',exact:true}).waitFor();
  await page.keyboard.press('Escape');check(await page.locator('.widget-board').count()===0,'Escape unmounts board');
  await page.keyboard.press('Control+Alt+w');await page.getByRole('heading',{name:'Мой день',exact:true}).waitFor();
  check(await page.getByRole('textbox',{name:'Задача для фокуса'}).inputValue()==='Подготовить презентацию','Task preserved');
  check(await page.getByRole('button',{name:'Пауза',exact:true}).isVisible(),'Running timer preserved');
  await page.getByRole('button',{name:'Пауза',exact:true}).click();await page.getByRole('button',{name:'Сбросить таймер'}).click();
  check(await page.getByRole('timer').innerText()==='25:00','Timer reset');
  await page.getByRole('button',{name:'Неделя',exact:true}).click();check(await page.locator('.cal-week-head>button').count()===7,'Week timeline days');
  await page.getByRole('button',{name:'Месяц',exact:true}).click();check(await page.locator('.wb-month>button').count()===42,'Month grid');
  const month=await page.locator('.wb-calendar h2').innerText();await page.locator('.wb-month').hover();await page.mouse.wheel(0,150);
  await page.waitForFunction(old=>document.querySelector('.wb-calendar h2').textContent!==old,month);check(true,'Wheel changes period');
  await page.locator('.wb-nav').getByRole('button',{name:'Сегодня',exact:true}).click();
  await page.locator('.wb-today .wb-event').first().click();await page.getByRole('dialog').waitFor();await page.keyboard.press('Tab');
  check(await page.getByRole('button',{name:'Закрыть событие'}).evaluate(e=>e===document.activeElement),'Detail focus stays inside');
  await page.keyboard.press('Escape');check(await page.getByRole('dialog').count()===0&&await page.locator('.widget-board').count()===1,'Detail closes before board');
  await settings();await page.getByRole('button',{name:'Задать своё сочетание…'}).click();
  await page.getByRole('button',{name:'Запись сочетания',exact:true}).press('Control+Shift+k');await page.getByRole('button',{name:'Сохранить',exact:true}).click();
  check(await page.getByRole('combobox',{name:'Горячая клавиша виджетов'}).inputValue()==='custom:6:75','Custom shortcut saved');
  await page.getByRole('checkbox',{name:'Фокус',exact:true}).uncheck();await page.getByRole('button',{name:'К виджетам'}).click();
  check(await page.locator('.wb-focus').count()===0,'Widget disabled');await page.keyboard.press('Control+Shift+k');
  check(await page.locator('.widget-board').count()===0,'Custom shortcut hides board');await go();
  check(await page.locator('.wb-focus').count()===0,'Widget choice persists after reload');await settings();
  await page.getByRole('checkbox',{name:'Фокус',exact:true}).check();await page.getByRole('combobox',{name:'Горячая клавиша виджетов'}).selectOption('custom:3:87');
  await page.getByRole('button',{name:'К виджетам'}).click();
  await page.setViewportSize({width:390,height:844});
  check(await page.locator('.widget-board').evaluate(e=>e.scrollWidth===e.clientWidth),'No horizontal overflow at 390px');
  await page.getByRole('button',{name:'Начать',exact:true}).scrollIntoViewIfNeeded();check(await page.getByRole('button',{name:'Начать',exact:true}).isVisible(),'Narrow focus controls reachable');
  await page.setViewportSize({width:620,height:480});await go('&widget-conflict');await settings();
  await page.getByRole('button',{name:'Подключить повторно'}).click();check(await page.locator('.search-shortcut-conflict').isVisible(),'Shortcut conflict and retry');
  check(await page.locator('.widget-board').evaluate(e=>e.scrollWidth===e.clientWidth),'Small settings window fits');
  await go('&save-error');await settings();await page.getByRole('checkbox',{name:'Фокус',exact:true}).click();
  await page.getByRole('alert').waitFor();check(await page.getByRole('checkbox',{name:'Фокус',exact:true}).isChecked(),'Failed save preserves checkbox');
  await page.getByRole('button',{name:'Задать своё сочетание…'}).click();await page.getByRole('button',{name:'Запись сочетания',exact:true}).press('Control+Shift+j');
  await page.getByRole('button',{name:'Сохранить',exact:true}).click();check(await page.getByRole('combobox',{name:'Горячая клавиша виджетов'}).inputValue()==='custom:3:87','Failed save preserves shortcut');
  await page.getByRole('button',{name:'Отмена',exact:true}).click();check(await page.evaluate(()=>document.documentElement.dataset.shortcutRecording==='false'),'Recorder released on cancel');
  await go('&calendar-empty');check(await page.getByRole('button',{name:'Подключить календарь',exact:true}).count()===2,'Empty calendar connection actions');
  await go('&calendar-offline');await page.locator('.wb-today .wb-event').first().waitFor();await page.getByRole('button',{name:'Обновить календарь',exact:true}).click();
  await page.waitForFunction(()=>document.querySelector('.wb-footer').textContent.includes('Не удалось обновить календарь'));
  check(await page.locator('.wb-today .wb-event').count()>0,'Offline retains cached events and reports error');
  await go('&capture-error');await settings();await page.getByRole('button',{name:'Задать своё сочетание…'}).click();await page.getByRole('alert').waitFor();
  check(await page.getByRole('button',{name:'Запись сочетания',exact:true}).count()===0,'Recorder failure stays recoverable');
  await page.evaluate(()=>{localStorage.setItem('bloom-language','en');const s=JSON.parse(localStorage.getItem('dinox-v4-demo-settings')||'{}');s['bloom-language']='en';localStorage.setItem('dinox-v4-demo-settings',JSON.stringify(s));});
  await page.goto(base);await page.getByRole('heading',{name:'My day',exact:true}).waitFor();check(true,'English interface');
  await page.evaluate(()=>{localStorage.setItem('bloom-language','ru');const s=JSON.parse(localStorage.getItem('dinox-v4-demo-settings')||'{}');s['bloom-language']='ru';localStorage.setItem('dinox-v4-demo-settings',JSON.stringify(s));});
  await page.setViewportSize({width:1280,height:920});await go();
  await settings();
  await page.getByRole('combobox',{name:'Затемнение фона'}).selectOption('45');
  await page.waitForFunction(()=>getComputedStyle(document.querySelector('.widget-board')).backgroundColor==='rgba(0, 0, 0, 0.45)');
  check(true,'Backdrop changes live');
  await go();
  check(await page.locator('.widget-board').evaluate(e=>getComputedStyle(e).backgroundColor==='rgba(0, 0, 0, 0.45)'),'Backdrop persists after reopening');
  await settings();await page.getByRole('combobox',{name:'Затемнение фона'}).selectOption('100');
  await page.waitForFunction(()=>getComputedStyle(document.querySelector('.widget-board')).backgroundColor==='rgb(0, 0, 0)');
  check(true,'Opaque backdrop available');
  await page.getByRole('combobox',{name:'Затемнение фона'}).selectOption('70');
  await go('&save-error');await settings();await page.getByRole('combobox',{name:'Затемнение фона'}).selectOption('45');
  await page.getByRole('alert').waitFor();
  check(await page.getByRole('combobox',{name:'Затемнение фона'}).inputValue()==='70','Failed opacity save preserves previous choice');
  await go();
  for(const size of [{width:1920,height:1080},{width:1440,height:900},{width:800,height:600},{width:390,height:844}]){
    await page.setViewportSize(size);
    check(await page.locator('.widget-board').evaluate(e=>{const r=e.getBoundingClientRect();return r.x===0&&r.y===0&&r.width===innerWidth&&r.height===innerHeight&&e.scrollWidth===e.clientWidth;}),`Full screen without overflow at ${size.width}x${size.height}`);
    check(await page.getByRole('button',{name:'Закрыть виджеты'}).evaluate(e=>{const r=e.getBoundingClientRect();return r.top>=0&&r.bottom<=innerHeight;}),`Close stays reachable at ${size.width}x${size.height}`);
  }
  await page.setViewportSize({width:1440,height:1000});await go();
  return {passed:checks.length,checks};
}
