use super::*;
const ROOT:&str="https://caldav.yandex.ru/";
fn url(href:&str)->Result<reqwest::Url,String>{let u=reqwest::Url::parse(ROOT).unwrap().join(href).map_err(|_|"Invalid CalDAV address")?;if u.scheme()!="https"||u.host_str()!=Some("caldav.yandex.ru")||u.port_or_known_default()!=Some(443)||!u.username().is_empty()||u.password().is_some()||u.fragment().is_some(){return Err("Unexpected CalDAV host".into());}Ok(u)}
fn text<'a>(node:roxmltree::Node<'a,'a>,name:&str)->Option<&'a str>{node.descendants().find(|n|n.is_element()&&n.tag_name().name()==name).and_then(|n|n.text())}
fn href(xml:&str,property:&str)->Result<String,String>{let doc=roxmltree::Document::parse(xml).map_err(|_|"Invalid CalDAV XML")?;doc.descendants().find(|n|n.is_element()&&n.tag_name().name()==property).and_then(|n|text(n,"href")).map(str::to_owned).ok_or("Calendar discovery is unavailable".into())}
async fn request(a:&Account,method:&str,href:&str,body:String,depth:&str)->Result<reqwest::Response,String>{let mut request=client()?.request(reqwest::Method::from_bytes(method.as_bytes()).unwrap(),url(href)?).header("Depth",depth).header("Content-Type","application/xml; charset=utf-8").body(body);request=if a.client_id.is_empty(){request.basic_auth(&a.username,Some(&a.secret))}else{request.header("Authorization",format!("OAuth {}",a.access))};request.send().await.map_err(|_|"Yandex is offline; cached calendars are unchanged".into())}
pub async fn discover(a:&mut Account)->Result<(),String>{
 let principal=response(request(a,"PROPFIND",ROOT,"<d:propfind xmlns:d='DAV:'><d:prop><d:current-user-principal/></d:prop></d:propfind>".into(),"0").await?).await?;
 let principal=href(&principal,"current-user-principal")?;a.username=url(&principal)?.to_string();
 let home=response(request(a,"PROPFIND",&principal,"<d:propfind xmlns:d='DAV:' xmlns:c='urn:ietf:params:xml:ns:caldav'><d:prop><c:calendar-home-set/></d:prop></d:propfind>".into(),"0").await?).await?;
 let home=href(&home,"calendar-home-set")?;
 let xml=response(request(a,"PROPFIND",&home,"<d:propfind xmlns:d='DAV:' xmlns:c='urn:ietf:params:xml:ns:caldav'><d:prop><d:displayname/><d:resourcetype/><d:current-user-privilege-set/><c:supported-calendar-component-set/></d:prop></d:propfind>".into(),"1").await?).await?;
 a.collections=parse_collections(&xml)?;if a.collections.is_empty(){return Err("Yandex returned no accessible calendars".into());}Ok(())
}
fn parse_collections(xml:&str)->Result<Vec<Collection>,String>{let doc=roxmltree::Document::parse(xml).map_err(|_|"Invalid CalDAV response")?;let mut out=vec![];for r in doc.descendants().filter(|n|n.is_element()&&n.tag_name().name()=="response"){
 let props:Vec<_>=r.children().filter(|n|n.is_element()&&n.tag_name().name()=="propstat"&&text(*n,"status").is_some_and(|s|s.contains(" 200 "))).collect();
 if !props.iter().any(|p|p.descendants().any(|n|n.is_element()&&n.tag_name().name()=="calendar")){continue;}
 let id=r.children().find(|n|n.is_element()&&n.tag_name().name()=="href").and_then(|n|n.text()).ok_or("Missing calendar address")?;let id=url(id)?.to_string();let name=props.iter().find_map(|p|text(*p,"displayname")).unwrap_or("Yandex").to_owned();let writable=props.iter().any(|p|p.descendants().any(|n|n.is_element()&&["write","all","bind"].contains(&n.tag_name().name())));
 for (component,kind) in [("VEVENT","event"),("VTODO","task")]{if props.iter().any(|p|p.descendants().any(|n|n.is_element()&&n.tag_name().name()=="comp"&&n.attribute("name")==Some(component))){out.push(Collection{id:id.clone(),name:name.clone(),kind:kind.into(),writable,enabled:true,ics:String::new(),items:vec![],checked:0});}}
 }Ok(out)}
pub async fn token(a:&mut Account)->Result<(),String>{
 if !a.client_id.is_empty()&&a.expires<=now()+90{let v=oauth_form("token",&[("grant_type","refresh_token"),("refresh_token",&a.refresh),("client_id",&a.client_id),("client_secret",&a.client_secret)]).await?;a.access=v["access_token"].as_str().ok_or("Yandex access expired; reconnect")?.into();if let Some(r)=v["refresh_token"].as_str(){a.refresh=r.into();}a.expires=now()+v["expires_in"].as_u64().unwrap_or(3600);}
 Ok(())
}
pub async fn refresh(a:&mut Account)->Result<(),String>{
 token(a).await?;
 let mut collections=a.collections.clone();for c in &mut collections{let component=if c.kind=="task"{"VTODO"}else{"VEVENT"};let xml=response(request(a,"REPORT",&c.id,format!("<c:calendar-query xmlns:d='DAV:' xmlns:c='urn:ietf:params:xml:ns:caldav'><d:prop><d:getetag/><c:calendar-data/></d:prop><c:filter><c:comp-filter name='VCALENDAR'><c:comp-filter name='{component}'/></c:comp-filter></c:filter></c:calendar-query>"),"1").await?).await?;let doc=roxmltree::Document::parse(&xml).map_err(|_|"Invalid calendar XML")?;
 let mut body=String::new();for r in doc.descendants().filter(|n|n.is_element()&&n.tag_name().name()=="propstat") {if !text(r,"status").is_some_and(|s|s.contains(" 200 ")){continue;}for node in r.descendants().filter(|n|n.is_element()&&n.tag_name().name()=="calendar-data"){if let Some(ics)=node.text(){let lines:Vec<_>=ics.lines().collect();let mut inside=0;for line in lines{if ["BEGIN:VEVENT","BEGIN:VTODO","BEGIN:VTIMEZONE"].contains(&line){inside=1;}else if inside>0&&line.starts_with("BEGIN:"){inside+=1;}if inside>0{body.push_str(line);body.push_str("\r\n");if line.starts_with("END:"){inside-=1;}}}}}}
 c.ics=format!("BEGIN:VCALENDAR\r\nVERSION:2.0\r\n{body}END:VCALENDAR\r\n");c.checked=now();}a.collections=collections;Ok(())
}
fn escape(value:&str)->String{value.replace('\\',"\\\\").replace('\r',"").replace('\n',"\\n").replace(';',"\\;").replace(',',"\\,")}
fn date(value:&str,all_day:bool)->Result<String,String>{if all_day{Ok(format!(";VALUE=DATE:{}",value.replace('-',"")))}else{let time=chrono::DateTime::parse_from_rfc3339(value).map_err(|_|"Invalid time")?;Ok(format!(":{}",time.with_timezone(&chrono::Utc).format("%Y%m%dT%H%M%SZ")))}}
fn content(d:&Draft)->Result<String,String>{let component=if d.kind=="task"{"VTODO"}else{"VEVENT"};let mut lines=vec!["BEGIN:VCALENDAR".into(),"VERSION:2.0".into(),"PRODID:-//Dinox//Calendar//EN".into(),format!("BEGIN:{component}"),format!("UID:{}@dinox",d.request_id),format!("DTSTAMP:{}",chrono::Utc::now().format("%Y%m%dT%H%M%SZ")),format!("SUMMARY:{}",escape(&d.title)),format!("DESCRIPTION:{}",escape(&d.description))];if let Some(start)=&d.start{lines.push(format!("{}{}",if d.kind=="task"{"DUE"}else{"DTSTART"},date(start,d.all_day)?));}if let Some(end)=&d.end{if d.kind=="event"{lines.push(format!("DTEND{}",date(end,d.all_day)?));}}if d.kind=="task"{lines.push("STATUS:NEEDS-ACTION".into());}lines.push(format!("END:{component}"));lines.push("END:VCALENDAR".into());
 // RFC 5545 folds by octets without splitting UTF-8 characters.
 let mut out=String::new();for line in lines{let mut width=0;for ch in line.chars(){if width+ch.len_utf8()>75{out.push_str("\r\n ");width=1;}out.push(ch);width+=ch.len_utf8();}out.push_str("\r\n");}Ok(out)}
pub async fn create(a:&Account,d:&Draft)->Result<String,String>{let base=url(&d.collection_id)?;if !base.path().ends_with('/'){return Err("Rejected: invalid collection path".into());}let target=base.join(&format!("{}.ics",d.request_id)).map_err(|_|"Invalid resource")?;let mut r=client()?.put(target.clone()).header("If-None-Match","*").header("Content-Type","text/calendar; charset=utf-8").body(content(d)?);r=if a.client_id.is_empty(){r.basic_auth(&a.username,Some(&a.secret))}else{r.header("Authorization",format!("OAuth {}",a.access))};let result=r.send().await.map_err(|_|"Creation result is uncertain; check Yandex before creating another copy")?;if result.status().is_client_error()&&result.status().as_u16()!=408{return Err(format!("Rejected: Yandex HTTP {}. Refresh calendar permissions.",result.status().as_u16()));}response(result).await?;Ok(target.to_string())}
async fn oauth_form(path:&str,fields:&[(&str,&str)])->Result<Value,String>{let encoded=reqwest::Url::parse_with_params("https://example.com",fields).unwrap().query().unwrap_or("").to_owned();let r=client()?.post(format!("https://oauth.yandex.ru/{path}")).header("Content-Type","application/x-www-form-urlencoded").body(encoded).send().await.map_err(|_|"Yandex sign-in connection failed")?;let status=r.status();let text=r.text().await.map_err(|_|"Invalid sign-in response")?;if text.len()>65536{return Err("Invalid sign-in response".into());}let v:Value=serde_json::from_str(&text).map_err(|_|"Invalid sign-in response")?;if !status.is_success()&&v["error"]!="authorization_pending"&&v["error"]!="slow_down"{return Err("Yandex denied sign-in. Check application approval and reconnect.".into());}Ok(v)}
pub async fn authorize(app:&AppHandle)->Result<Account,String>{
 let id=option_env!("DINOX_YANDEX_CLIENT_ID").unwrap_or("");let secret=option_env!("DINOX_YANDEX_CLIENT_SECRET").unwrap_or("");if id.is_empty()||option_env!("DINOX_YANDEX_CALDAV_APPROVED")!=Some("true"){return Err("Yandex sign-in is not enabled by the publisher in this build. ICS subscriptions remain available.".into());}
 let codes=oauth_form("device/code",&[("client_id",id)]).await?;let device=codes["device_code"].as_str().ok_or("Missing device code")?;let user=codes["user_code"].as_str().ok_or("Missing user code")?;let _=app.emit("calendar-auth-code",json!({"provider":"yandex","code":user}));use tauri_plugin_opener::OpenerExt;app.opener().open_url("https://oauth.yandex.ru/device",None::<&str>).map_err(|_|"Cannot open sign-in")?;let deadline=now()+codes["expires_in"].as_u64().unwrap_or(300).min(600);let mut interval=codes["interval"].as_u64().unwrap_or(5).max(5);while now()<deadline{if super::cancelled(){return Err("Sign-in cancelled".into());}tokio::time::sleep(Duration::from_secs(interval)).await;let v=oauth_form("token",&[("grant_type","device_code"),("code",device),("client_id",id),("client_secret",secret)]).await?;if v["error"]=="slow_down"{interval=(interval+5).min(30);continue;}if v["error"]=="authorization_pending"{continue;}let access=v["access_token"].as_str().ok_or("Sign-in failed")?.to_owned();return Ok(Account{id:uuid::Uuid::new_v4().to_string(),provider:"yandex".into(),label:"Yandex".into(),username:String::new(),secret:String::new(),client_id:id.into(),client_secret:secret.into(),refresh:v["refresh_token"].as_str().unwrap_or("").into(),access,expires:now()+v["expires_in"].as_u64().unwrap_or(3600),collections:vec![]});}Err("Yandex sign-in timed out".into())
}
#[cfg(test)]mod tests{use super::*;#[test]fn remote_hrefs_cannot_leak_credentials(){assert!(url("https://evil.example/path").is_err());assert!(url("http://caldav.yandex.ru/").is_err());assert!(url("/calendars/test/").is_ok());}#[test]fn ics_text_is_escaped_and_folded(){let d=Draft{request_id:uuid::Uuid::new_v4().to_string(),account_id:"a".into(),collection_id:"b".into(),kind:"task".into(),title:"Тест\nBEGIN:VEVENT".into(),description:"Ж".repeat(100),start:Some("2026-09-28".into()),end:None,all_day:true};let s=content(&d).unwrap();assert!(s.contains("DUE;VALUE=DATE:20260928"));assert!(s.contains("Тест\\nBEGIN:VEVENT"));assert!(s.lines().all(|l|l.len()<=75));}}


#[cfg(test)]
mod protocol_tests {
 use super::*;
 #[test]
 fn discovery_respects_advertised_components_and_read_only_access(){
  let xml="<d:multistatus xmlns:d='DAV:' xmlns:c='urn:ietf:params:xml:ns:caldav'><d:response><d:href>/calendars/demo/</d:href><d:propstat><d:prop><d:resourcetype><c:calendar/></d:resourcetype><d:displayname>Demo</d:displayname><c:supported-calendar-component-set><c:comp name='VEVENT'/></c:supported-calendar-component-set></d:prop><d:status>HTTP/1.1 200 OK</d:status></d:propstat><d:propstat><d:prop><d:current-user-privilege-set><d:all/></d:current-user-privilege-set></d:prop><d:status>HTTP/1.1 403 Forbidden</d:status></d:propstat></d:response></d:multistatus>";
  let c=parse_collections(xml).unwrap();assert_eq!(c.len(),1);assert_eq!(c[0].kind,"event");assert!(!c[0].writable);
  let both=xml.replace("<c:comp name='VEVENT'/>","<c:comp name='VEVENT'/><c:comp name='VTODO'/>");assert_eq!(parse_collections(&both).unwrap().len(),2);
 }
 #[test]
 fn event_payload_keeps_exclusive_end_and_converts_timed_dates_to_utc(){
  let mut d=Draft{request_id:uuid::Uuid::new_v4().to_string(),account_id:"a".into(),collection_id:"b".into(),kind:"event".into(),title:"Test".into(),description:String::new(),start:Some("2026-09-28".into()),end:Some("2026-09-29".into()),all_day:true};
  let s=content(&d).unwrap();assert!(s.contains("DTEND;VALUE=DATE:20260929"));assert!(s.contains("BEGIN:VEVENT"));
  d.all_day=false;d.start=Some("2026-09-28T12:00:00+03:00".into());d.end=Some("2026-09-28T13:00:00+03:00".into());assert!(content(&d).unwrap().contains("DTSTART:20260928T090000Z"));
 }
}
