import {calendarError} from './errors';
import {useEffect,useState} from 'react';
import {invoke} from '@tauri-apps/api/core';
import {listen} from '@tauri-apps/api/event';
import {RefreshCw,Unplug,Check,CalendarDays} from 'lucide-react';
import {tx} from '../desktopText';
import type {CalendarAccount} from './accounts';
import './sync.css';
export function CalendarAccounts(){
 const [accounts,setAccounts]=useState<CalendarAccount[]>([]),[config,setConfig]=useState<{google:boolean;yandex:boolean;googleMode?:string}>({google:false,yandex:false}),[busy,setBusy]=useState(''),[error,setError]=useState(''),[code,setCode]=useState(''),[confirm,setConfirm]=useState('');
 const load=()=>Promise.all([invoke<CalendarAccount[]>('calendar_accounts').then(setAccounts),invoke<typeof config>('calendar_google_config').then(setConfig)]);
 useEffect(()=>{void load().catch(e=>setError(calendarError(e)));const off=listen<{code:string}>('calendar-auth-code',e=>setCode(e.payload.code));return()=>{void off.then(f=>f());};},[]);
 const run=async(key:string,operation:()=>Promise<unknown>)=>{setBusy(key);setError('');setCode('');try{await operation();await load();}catch(e){setError(calendarError(e));}finally{setBusy('');setCode('');}};
 return <section className="cs-connect"><header><CalendarDays size={21}/><div><h3>{tx('Ваши календари и задачи','Your calendars and tasks')}</h3><p>{tx('Подключите аккаунт, чтобы видеть задачи и создавать записи прямо здесь.','Connect an account to see tasks and create entries here.')}</p></div></header>
 <p className="cs-footnote">{tx('Подключение бесплатно. Dinox обращается к сервису напрямую с вашего компьютера; отдельный аккаунт Dinox не нужен.','Connection is free. Dinox contacts the provider directly from your computer; no separate Dinox account is needed.')}</p>
 {config.google&&config.googleMode==='testing'&&<p className="cs-footnote" role="note">{tx('Google-вход пока в тестовом режиме: доступны только аккаунты, добавленные разработчиком. Google может запросить повторное подключение через 7 дней. Подписки ICS доступны без участия в тестировании.','Google sign-in is currently in testing: only accounts added by the developer can connect. Google may require reconnection after 7 days. ICS subscriptions do not require test access.')}</p>}
 {config.google&&config.googleMode==='unverified'&&<p className="cs-footnote" role="note">{tx('Google-вход ещё не прошёл проверку Google: возможно предупреждение, действует лимит пользователей. Подписки ICS доступны независимо от этого лимита.','Google sign-in has not yet passed Google verification: a warning and a user cap apply. ICS subscriptions are independent of this cap.')}</p>}
 <div className="cs-providers">{(['google','yandex'] as const).map(provider=><div key={provider}><button disabled={!!busy||!config[provider]} onClick={()=>void run(provider,()=>invoke(`calendar_connect_${provider}`))}>{busy===provider?tx('Ожидаем разрешение…','Waiting for permission…'):`${tx('Подключить','Connect')} ${provider==='google'?'Google':'Яндекс'}`}</button><small>{config[provider]?tx('Разрешите доступ на странице сервиса. Пароль аккаунта Dinox не получает.','Allow access on the provider page. Dinox does not receive your account password.'):tx('Вход ещё не активирован разработчиком в этой сборке. Подписки по ссылке доступны ниже.','Sign-in has not been enabled by the publisher in this build. Link subscriptions remain available below.')}</small></div>)}</div>
 {code&&<p className="cs-code">{tx('Введите этот код на открывшейся странице Яндекса:','Enter this code on the Yandex page:')} <strong>{code}</strong></p>}
 {busy&&<p role="status">{tx('Первое подключение может занять несколько минут. Существующие подписки сохранены.','The first connection may take a few minutes. Existing subscriptions are retained.')}</p>}
 {(busy==='google'||busy==='yandex')&&<button onClick={()=>void invoke('calendar_cancel_auth')}>{tx('Отменить вход','Cancel sign-in')}</button>}{error&&<p role="alert" className="cs-error">{error}</p>}
 {accounts.map(a=><article className="cs-account" key={a.id}><div><strong>{a.label}</strong><small>{a.provider==='google'?'Google':'Яндекс'} · {a.collections.length} {tx('календарей и списков','calendars and lists')}</small></div><button aria-label={`${tx('Обновить','Refresh')}: ${a.label}`} disabled={!!busy} onClick={()=>void run(a.id,()=>invoke('calendar_account_refresh',{id:a.id}))}><RefreshCw size={16}/></button><button aria-label={`${tx('Отключить','Disconnect')}: ${a.label}`} disabled={!!busy} onClick={()=>setConfirm(a.id)}><Unplug size={16}/></button><ul>{a.collections.map(c=><li key={`${c.kind}:${c.id}`}><Check size={13}/>{c.name}<small>{c.kind==='task'?tx('Задачи','Tasks'):tx('События','Events')} · {c.writable?tx('чтение и создание','read and create'):tx('только чтение','read only')}</small></li>)}</ul>{confirm===a.id&&<div><p>{tx('Отключить от Dinox? Записи в исходном сервисе останутся.','Disconnect from Dinox? Original entries will remain.')}</p><button onClick={()=>void run(a.id,()=>invoke('calendar_account_remove',{id:a.id})).then(()=>setConfirm(''))}>{tx('Отключить аккаунт','Disconnect account')}</button><button onClick={()=>setConfirm('')}>{tx('Отмена','Cancel')}</button></div>}</article>)}
 <p className="cs-footnote">{tx('Google Tasks передаёт дату задачи без точного времени. Яндекс-задачи доступны, только если сервер предоставляет список задач.','Google Tasks provides a date without an exact time. Yandex tasks are available only when the server exposes a task collection.')}</p>
 </section>;
}
