import {useEffect,useRef,useState,lazy,Suspense,type CSSProperties} from 'react';
import {createPortal} from 'react-dom';
import {StickyNote as NoteIcon,Plus,Search,X,Trash2,ArrowLeft,CheckSquare,Pin,RotateCcw,Download,Maximize2} from 'lucide-react';
import {invoke} from '@tauri-apps/api/core';
import {tx} from '../desktopText';
import {locale} from '../i18n/core';
import {newNote,noteName,noteColors,documentText,filterNotes,type StickyNote} from './model';
import {useNotes,saveNote,retryNotes,resolveAsCopy,deletePermanently,waitForNotes} from './store';
import './notes.css';
const Editor=lazy(()=>import('./StickyEditor').then(module=>({default:module.StickyEditor})));
const name=(note:StickyNote)=>noteName(note)||tx('Без названия','Untitled');
const create=()=>{const note=newNote();saveNote(note);return note.id;};
function StoreStatus(){const state=useNotes();if(!state.error)return null;return <div className="dn-store-error" role="alert">{state.error==='conflict'?tx('Заметка изменена в другом окне. Ваш текст сохранён в черновике: создайте копию, чтобы не перезаписать чужие изменения.','This note changed in another window. Your draft is retained: save a copy to avoid overwriting it.'):state.error==='migration'?tx('Старую заметку не удалось прочитать. Исходная запись сохранена без изменений.','Could not read the previous note. Its original entry is preserved.'):state.error==='load'?tx('Не удалось открыть хранилище заметок. Перезагрузите панель.','Could not open notes storage. Reload the board.'):tx('Не удалось сохранить все изменения. Не закрывайте Dinox до повторного сохранения.','Some changes could not be saved. Keep Dinox open until saving succeeds.')}<button onClick={retryNotes}>{tx('Повторить сохранение','Retry saving')}</button></div>;}
async function downloadBackup(notes:StickyNote[]){document.documentElement.dataset.notesFilePicker='true';try{await invoke('notes_export_backup',{contents:JSON.stringify({format:'dinox-sticky-notes',version:1,notes},null,2)});}finally{delete document.documentElement.dataset.notesFilePicker;}}

export function StickyNotesWidget(){
  const state=useNotes(),[open,setOpen]=useState(false),[initial,setInitial]=useState<string|null>(null);
  const recent=filterNotes(state.notes,'');
  const show=(id:string|null)=>{setInitial(id);setOpen(true);};
  return <article className="wb-card wb-note dn-widget"><header><h2><NoteIcon size={17}/>{tx('Заметки','Notes')}</h2><div><button aria-label={tx('Все заметки','All notes')} onClick={()=>show(recent[0]?.id??null)}><Maximize2 size={16}/></button><button aria-label={tx('Новая заметка','New note')} disabled={!state.loaded} onClick={()=>show(create())}><Plus size={18}/></button></div></header>
    {!state.loaded?<p>{tx('Загрузка заметок…','Loading notes…')}</p>:recent.length?<div className="dn-widget-list">{recent.slice(0,4).map(note=><button key={note.id} style={{'--note-color':noteColors[note.color]} as CSSProperties} onClick={()=>show(note.id)}><strong>{note.pinned&&<Pin size={12}/>} {name(note)}</strong><span>{documentText(note.doc).slice(0,130)||tx('Пустая заметка','Empty note')}</span></button>)}</div>:<div className="dn-widget-empty"><p>{tx('Мысли, списки и изображения — в отдельных стикерах.','Ideas, lists and images — on individual sticky notes.')}</p><button onClick={()=>show(create())}>{tx('Создать первую заметку','Create your first note')}</button></div>}
    <button className="dn-widget-more" onClick={()=>show(recent[0]?.id??null)}>{tx('Открыть библиотеку','Open library')} · {recent.length}</button><StoreStatus/>
    {open&&createPortal(<NotesLibrary initial={initial} onClose={()=>setOpen(false)}/>,document.body)}
  </article>;
}

export function NotesLibrary({initial,onClose}:{initial:string|null;onClose:()=>void}){
  const state=useNotes(),[active,setActive]=useState<string|null>(initial),[query,setQuery]=useState(''),[trash,setTrash]=useState(false),[color,setColor]=useState('all'),[multi,setMulti]=useState(false),[selected,setSelected]=useState<string[]>([]),[limit,setLimit]=useState(60),[confirm,setConfirm]=useState(false),[error,setError]=useState(''),[lastDeleted,setLastDeleted]=useState<string[]>([]);
  const root=useRef<HTMLDivElement>(null),search=useRef<HTMLInputElement>(null),previous=useRef(document.activeElement as HTMLElement|null);
  const notes=filterNotes(state.notes,query,trash,color),chosen=state.notes.find(n=>n.id===active&&Boolean(n.deletedAt)===trash);
  const close=async()=>{try{await waitForNotes();onClose();}catch{setError(tx('Сначала сохраните изменения или скачайте резервную копию.','Save your changes or download a backup first.'));}};
  useEffect(()=>{root.current?.querySelector<HTMLButtonElement>('.dn-close')?.focus();return()=>{previous.current?.focus();};},[]);
  useEffect(()=>{setLimit(60);setSelected([]);setConfirm(false);},[query,trash,color]);
  const remove=(ids:string[])=>{setError('');const now=Date.now();state.notes.filter(n=>ids.includes(n.id)).forEach(n=>saveNote({...n,deletedAt:now}));setLastDeleted(ids);setActive(null);setSelected([]);};
  const restore=(ids:string[])=>{state.notes.filter(n=>ids.includes(n.id)).forEach(n=>saveNote({...n,deletedAt:null}));setSelected([]);setLastDeleted([]);};
  const selectNote=(id:string)=>{if(multi)setSelected(old=>old.includes(id)?old.filter(v=>v!==id):[...old,id]);else setActive(id);};
  return <div className="dn-backdrop"><div className="dn-notes" ref={root} role="dialog" aria-modal="true" aria-label={tx('Библиотека заметок','Notes library')} onKeyDown={e=>{
    if(e.key==='Escape'){e.preventDefault();e.stopPropagation();if(confirm)setConfirm(false);else if(active&&matchMedia('(max-width:700px)').matches)setActive(null);else void close();}
    if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='n'){e.preventDefault();e.stopPropagation();setTrash(false);setQuery('');setActive(create());}
    if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='f'){e.preventDefault();e.stopPropagation();setActive(null);search.current?.focus();}
    if(e.key==='Tab'){const fields=Array.from(root.current?.querySelectorAll<HTMLElement>('button:not(:disabled),input:not(:disabled),select:not(:disabled),[contenteditable=true]')||[]).filter(el=>el.getClientRects().length);const first=fields[0],last=fields[fields.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus();}}
  }}>
    <header className="dn-library-header"><div><span className="dn-brand">dinox</span><h2>{tx('Заметки','Notes')}</h2></div><div className="dn-header-actions"><button disabled={!state.loaded} onClick={()=>{setTrash(false);setQuery('');setMulti(false);setActive(create());}}><Plus size={18}/>{tx('Новая заметка','New note')}</button><button aria-label={tx('Скачать резервную копию заметок','Download notes backup')} onClick={()=>{void downloadBackup(state.notes).catch(()=>setError(tx('Не удалось сохранить резервную копию.','Could not save backup.')));}}><Download size={18}/></button><button className="dn-close" aria-label={tx('Закрыть библиотеку','Close library')} onClick={()=>void close()}><X size={20}/></button></div></header>
    <StoreStatus/>{error&&<div className="dn-store-error" role="alert">{error}</div>}
    <div className={'dn-library-body'+(active?' dn-has-editor':'')}>
      <aside className="dn-sidebar"><label className="dn-search"><Search size={17}/><input ref={search} aria-label={tx('Поиск заметок','Search notes')} placeholder={tx('Поиск по заметкам','Search notes')} value={query} onChange={e=>setQuery(e.target.value)}/></label>
        <div className="dn-filter-row"><button aria-pressed={!trash} onClick={()=>{setTrash(false);setActive(null);}}>{tx('Все','All')} · {state.notes.filter(n=>!n.deletedAt).length}</button><button aria-pressed={trash} onClick={()=>{setTrash(true);setActive(null);}}><Trash2 size={14}/>{tx('Корзина','Trash')}</button><button aria-label={tx('Выбрать несколько заметок','Select multiple notes')} aria-pressed={multi} onClick={()=>{setMulti(v=>!v);setSelected([]);}}><CheckSquare size={16}/></button></div>
        <select aria-label={tx('Фильтр по цвету','Filter by color')} value={color} onChange={e=>setColor(e.target.value)}><option value="all">{tx('Все цвета','All colors')}</option>{Object.keys(noteColors).map((c,index)=><option key={c} value={c}>{[tx('Жёлтые','Yellow'),tx('Зелёные','Green'),tx('Синие','Blue'),tx('Фиолетовые','Purple'),tx('Розовые','Pink'),tx('Серые','Gray')][index]}</option>)}</select>
        {multi&&<div className="dn-bulk"><button onClick={()=>setSelected(selected.length===notes.length?[]:notes.map(n=>n.id))}>{tx('Выбрать все','Select all')}</button><span>{selected.length}</span>{trash?<><button disabled={!selected.length} onClick={()=>restore(selected)}>{tx('Восстановить','Restore')}</button><button disabled={!selected.length||state.unsaved} onClick={()=>setConfirm(true)}>{tx('Удалить навсегда','Delete permanently')}</button></>:<button disabled={!selected.length} onClick={()=>remove(selected)}>{tx('В корзину','Move to trash')}</button>}</div>}
        {confirm&&<div className="dn-confirm" role="alert"><p>{tx('Удалить выбранные заметки без возможности восстановления?','Permanently delete the selected notes?')}</p><button onClick={()=>{void deletePermanently(selected).then(()=>{setConfirm(false);setSelected([]);setActive(null);}).catch(()=>setError(tx('Не удалось удалить. Обновите список и повторите.','Could not delete. Refresh the list and retry.')));}}>{tx('Подтвердить удаление','Confirm deletion')}</button><button onClick={()=>setConfirm(false)}>{tx('Отмена','Cancel')}</button></div>}
        <div className="dn-note-list">{notes.slice(0,limit).map(note=><button className={'dn-note-preview'+(active===note.id?' active':'')} key={note.id} style={{'--note-color':noteColors[note.color]} as CSSProperties} aria-label={`${tx('Открыть заметку','Open note')}: ${name(note)}`} aria-pressed={multi?selected.includes(note.id):active===note.id} onClick={()=>selectNote(note.id)}>
          <div><strong>{multi&&(selected.includes(note.id)?'☑ ':'☐ ')}{note.pinned&&<Pin size={12}/>} {name(note)}</strong><time>{new Date(note.updated).toLocaleDateString(locale(),{day:'numeric',month:'short'})}</time></div><p>{documentText(note.doc).slice(0,240)||tx('Пустая заметка','Empty note')}</p>{note.doc.content?.some(n=>n.type==='image')&&<small>{tx('Есть изображение','Contains image')}</small>}
        </button>)}{notes.length>limit&&<button onClick={()=>setLimit(n=>n+60)}>{tx('Показать ещё','Show more')}</button>}{!notes.length&&<p className="dn-empty">{query?tx('Ничего не найдено','No matches'):trash?tx('Корзина пуста','Trash is empty'):tx('Начните с новой заметки','Start with a new note')}</p>}</div>
        <footer>{tx('Локальные заметки · без синхронизации OneNote','Local notes · no OneNote sync')}</footer>
      </aside>
      <main className="dn-workspace">{chosen?<><div className="dn-workspace-nav"><button className="dn-back-list" onClick={()=>setActive(null)}><ArrowLeft size={17}/>{tx('К списку','Back to list')}</button>{trash&&<button onClick={()=>restore([chosen.id])}><RotateCcw size={16}/>{tx('Восстановить заметку','Restore note')}</button>}{state.error==='conflict'&&<button onClick={()=>{const copy=resolveAsCopy(chosen.id);if(copy)setActive(copy.id);}}>{tx('Сохранить отдельную копию','Save as a separate copy')}</button>}</div><Suspense fallback={<p>{tx('Загрузка редактора…','Loading editor…')}</p>}><Editor key={chosen.id} note={chosen} onOpenCopy={id=>{setTrash(false);setActive(id);}} onDelete={()=>remove([chosen.id])} onPopout={()=>{void waitForNotes(chosen.id).then(()=>invoke('notes_open_window',{id:chosen.id})).catch(()=>setError(tx('Не удалось открыть отдельное окно. Проверьте сохранение заметки.','Could not open a separate window. Check that the note is saved.')));}}/></Suspense></>:<div className="dn-welcome"><NoteIcon size={42}/><h3>{tx('Место для ваших мыслей','A place for your thoughts')}</h3><p>{tx('Выберите стикер слева или создайте новый. Цвет, текст и изображения сохраняются автоматически.','Choose a note or create one. Color, text and images save automatically.')}</p><button onClick={()=>{setTrash(false);setQuery('');setActive(create());}}><Plus size={17}/>{tx('Новая заметка','New note')}</button></div>}</main>
    </div>
    {!!lastDeleted.length&&!trash&&<div className="dn-undo-bar">{tx('Заметки перемещены в корзину','Notes moved to trash')}<button onClick={()=>restore(lastDeleted)}><RotateCcw size={14}/>{tx('Отменить удаление','Undo deletion')}</button></div>}
  </div></div>;
}

export function StickyWindow({id,onClose}:{id:string;onClose:()=>void}){
  const state=useNotes(),note=state.notes.find(n=>n.id===id),[error,setError]=useState(''),[top,setTop]=useState(false);
  return <div className="dn-notes dn-popout" onKeyDown={e=>{if(e.key==='Escape'){e.preventDefault();e.stopPropagation();onClose();}}}><header className="dn-popout-header" data-tauri-drag-region><span data-tauri-drag-region>dinox · {tx('Заметка','Note')}</span><div><button aria-label={tx('Поверх других окон','Keep above other windows')} aria-pressed={top} onClick={()=>{void invoke('notes_set_top',{top:!top}).then(()=>setTop(v=>!v)).catch(()=>setError(tx('Не удалось изменить закрепление окна.','Could not change window pinning.')));}}><Pin size={16}/></button><button aria-label={tx('Закрыть заметку','Close note')} onClick={onClose}><X size={18}/></button></div></header><StoreStatus/>{error&&<p role="alert">{error}</p>}{state.error==='conflict'&&<button onClick={()=>{const copy=resolveAsCopy(id);if(copy)void waitForNotes(copy.id).then(()=>invoke('notes_open_window',{id:copy.id})).catch(()=>setError(tx('Не удалось открыть копию.','Could not open copy.')));}}>{tx('Сохранить отдельную копию','Save as a separate copy')}</button>}{note?<Suspense fallback={<p>{tx('Загрузка…','Loading…')}</p>}><Editor note={note} onOpenCopy={copy=>{void waitForNotes(copy).then(()=>invoke('notes_open_window',{id:copy})).catch(()=>setError(tx('Не удалось открыть копию.','Could not open the copy.')));}} onDelete={()=>saveNote({...note,deletedAt:Date.now()})}/>{note.deletedAt&&<button onClick={()=>saveNote({...note,deletedAt:null})}>{tx('Восстановить заметку','Restore note')}</button>}</Suspense>:<p className="dn-empty">{state.loaded?tx('Заметка удалена','Note was deleted'):tx('Загрузка…','Loading…')}</p>}</div>;
}
